---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forge-mi-ingress-base
spec:
  rules:
    - host: zak-cert.dso.numerique-interieur.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dso-demo-java
                port:
                  number: 8080
